package com.sap.cdc.bitsnbytes.ui.view.model

/**
 * Data class representing a country with its code, name, and flag
 */
data class Country(
    val code: String,
    val dialCode: String,
    val name: String,
    val flagEmoji: String
)

/**
 * Object containing all available countries for phone number selection
 */
object CountryData {
    val countries = listOf(
        Country("AD", "+376", "Andorra", "🇦🇩"),
        Country("AE", "+971", "United Arab Emirates", "🇦🇪"),
        Country("AF", "+93", "Afghanistan", "🇦🇫"),
        Country("AG", "+1", "Antigua and Barbuda", "🇦🇬"),
        Country("AI", "+1", "Anguilla", "🇦🇮"),
        Country("AL", "+355", "Albania", "🇦🇱"),
        Country("AM", "+374", "Armenia", "🇦🇲"),
        Country("AO", "+244", "Angola", "🇦🇴"),
        Country("AR", "+54", "Argentina", "🇦🇷"),
        Country("AS", "+1", "American Samoa", "🇦🇸"),
        Country("AT", "+43", "Austria", "🇦🇹"),
        Country("AU", "+61", "Australia", "🇦🇺"),
        Country("AW", "+297", "Aruba", "🇦🇼"),
        Country("AZ", "+994", "Azerbaijan", "🇦🇿"),
        Country("BA", "+387", "Bosnia and Herzegovina", "🇧🇦"),
        Country("BB", "+1", "Barbados", "🇧🇧"),
        Country("BD", "+880", "Bangladesh", "🇧🇩"),
        Country("BE", "+32", "Belgium", "🇧🇪"),
        Country("BF", "+226", "Burkina Faso", "🇧🇫"),
        Country("BG", "+359", "Bulgaria", "🇧🇬"),
        Country("BH", "+973", "Bahrain", "🇧🇭"),
        Country("BI", "+257", "Burundi", "🇧🇮"),
        Country("BJ", "+229", "Benin", "🇧🇯"),
        Country("BM", "+1", "Bermuda", "🇧🇲"),
        Country("BN", "+673", "Brunei", "🇧🇳"),
        Country("BO", "+591", "Bolivia", "🇧🇴"),
        Country("BR", "+55", "Brazil", "🇧🇷"),
        Country("BS", "+1", "Bahamas", "🇧🇸"),
        Country("BT", "+975", "Bhutan", "🇧🇹"),
        Country("BW", "+267", "Botswana", "🇧🇼"),
        Country("BY", "+375", "Belarus", "🇧🇾"),
        Country("BZ", "+501", "Belize", "🇧🇿"),
        Country("CA", "+1", "Canada", "🇨🇦"),
        Country("CD", "+243", "Democratic Republic of the Congo", "🇨🇩"),
        Country("CF", "+236", "Central African Republic", "🇨🇫"),
        Country("CG", "+242", "Republic of the Congo", "🇨🇬"),
        Country("CH", "+41", "Switzerland", "🇨🇭"),
        Country("CI", "+225", "Ivory Coast", "🇨🇮"),
        Country("CK", "+682", "Cook Islands", "🇨🇰"),
        Country("CL", "+56", "Chile", "🇨🇱"),
        Country("CM", "+237", "Cameroon", "🇨🇲"),
        Country("CN", "+86", "China", "🇨🇳"),
        Country("CO", "+57", "Colombia", "🇨🇴"),
        Country("CR", "+506", "Costa Rica", "🇨🇷"),
        Country("CU", "+53", "Cuba", "🇨🇺"),
        Country("CV", "+238", "Cape Verde", "🇨🇻"),
        Country("CY", "+357", "Cyprus", "🇨🇾"),
        Country("CZ", "+420", "Czech Republic", "🇨🇿"),
        Country("DE", "+49", "Germany", "🇩🇪"),
        Country("DJ", "+253", "Djibouti", "🇩🇯"),
        Country("DK", "+45", "Denmark", "🇩🇰"),
        Country("DM", "+1", "Dominica", "🇩🇲"),
        Country("DO", "+1", "Dominican Republic", "🇩🇴"),
        Country("DZ", "+213", "Algeria", "🇩🇿"),
        Country("EC", "+593", "Ecuador", "🇪🇨"),
        Country("EE", "+372", "Estonia", "🇪🇪"),
        Country("EG", "+20", "Egypt", "🇪🇬"),
        Country("ER", "+291", "Eritrea", "🇪🇷"),
        Country("ES", "+34", "Spain", "🇪🇸"),
        Country("ET", "+251", "Ethiopia", "🇪🇹"),
        Country("FI", "+358", "Finland", "🇫🇮"),
        Country("FJ", "+679", "Fiji", "🇫🇯"),
        Country("FK", "+500", "Falkland Islands", "🇫🇰"),
        Country("FM", "+691", "Micronesia", "🇫🇲"),
        Country("FO", "+298", "Faroe Islands", "🇫🇴"),
        Country("FR", "+33", "France", "🇫🇷"),
        Country("GA", "+241", "Gabon", "🇬🇦"),
        Country("GB", "+44", "United Kingdom", "🇬🇧"),
        Country("GD", "+1", "Grenada", "🇬🇩"),
        Country("GE", "+995", "Georgia", "🇬🇪"),
        Country("GF", "+594", "French Guiana", "🇬🇫"),
        Country("GG", "+44", "Guernsey", "🇬🇬"),
        Country("GH", "+233", "Ghana", "🇬🇭"),
        Country("GI", "+350", "Gibraltar", "🇬🇮"),
        Country("GL", "+299", "Greenland", "🇬🇱"),
        Country("GM", "+220", "Gambia", "🇬🇲"),
        Country("GN", "+224", "Guinea", "🇬🇳"),
        Country("GP", "+590", "Guadeloupe", "🇬🇵"),
        Country("GQ", "+240", "Equatorial Guinea", "🇬🇶"),
        Country("GR", "+30", "Greece", "🇬🇷"),
        Country("GT", "+502", "Guatemala", "🇬🇹"),
        Country("GU", "+1", "Guam", "🇬🇺"),
        Country("GW", "+245", "Guinea-Bissau", "🇬🇼"),
        Country("GY", "+592", "Guyana", "🇬🇾"),
        Country("HK", "+852", "Hong Kong", "🇭🇰"),
        Country("HN", "+504", "Honduras", "🇭🇳"),
        Country("HR", "+385", "Croatia", "🇭🇷"),
        Country("HT", "+509", "Haiti", "🇭🇹"),
        Country("HU", "+36", "Hungary", "🇭🇺"),
        Country("ID", "+62", "Indonesia", "🇮🇩"),
        Country("IE", "+353", "Ireland", "🇮🇪"),
        Country("IL", "+972", "Israel", "🇮🇱"),
        Country("IM", "+44", "Isle of Man", "🇮🇲"),
        Country("IN", "+91", "India", "🇮🇳"),
        Country("IO", "+246", "British Indian Ocean Territory", "🇮🇴"),
        Country("IQ", "+964", "Iraq", "🇮🇶"),
        Country("IR", "+98", "Iran", "🇮🇷"),
        Country("IS", "+354", "Iceland", "🇮🇸"),
        Country("IT", "+39", "Italy", "🇮🇹"),
        Country("JE", "+44", "Jersey", "🇯🇪"),
        Country("JM", "+1", "Jamaica", "🇯🇲"),
        Country("JO", "+962", "Jordan", "🇯🇴"),
        Country("JP", "+81", "Japan", "🇯🇵"),
        Country("KE", "+254", "Kenya", "🇰🇪"),
        Country("KG", "+996", "Kyrgyzstan", "🇰🇬"),
        Country("KH", "+855", "Cambodia", "🇰🇭"),
        Country("KI", "+686", "Kiribati", "🇰🇮"),
        Country("KM", "+269", "Comoros", "🇰🇲"),
        Country("KN", "+1", "Saint Kitts and Nevis", "🇰🇳"),
        Country("KP", "+850", "North Korea", "🇰🇵"),
        Country("KR", "+82", "South Korea", "🇰🇷"),
        Country("KW", "+965", "Kuwait", "🇰🇼"),
        Country("KY", "+1", "Cayman Islands", "🇰🇾"),
        Country("KZ", "+7", "Kazakhstan", "🇰🇿"),
        Country("LA", "+856", "Laos", "🇱🇦"),
        Country("LB", "+961", "Lebanon", "🇱🇧"),
        Country("LC", "+1", "Saint Lucia", "🇱🇨"),
        Country("LI", "+423", "Liechtenstein", "🇱🇮"),
        Country("LK", "+94", "Sri Lanka", "🇱🇰"),
        Country("LR", "+231", "Liberia", "🇱🇷"),
        Country("LS", "+266", "Lesotho", "🇱🇸"),
        Country("LT", "+370", "Lithuania", "🇱🇹"),
        Country("LU", "+352", "Luxembourg", "🇱🇺"),
        Country("LV", "+371", "Latvia", "🇱🇻"),
        Country("LY", "+218", "Libya", "🇱🇾"),
        Country("MA", "+212", "Morocco", "🇲🇦"),
        Country("MC", "+377", "Monaco", "🇲🇨"),
        Country("MD", "+373", "Moldova", "🇲🇩"),
        Country("ME", "+382", "Montenegro", "🇲🇪"),
        Country("MF", "+590", "Saint Martin", "🇲🇫"),
        Country("MG", "+261", "Madagascar", "🇲🇬"),
        Country("MH", "+692", "Marshall Islands", "🇲🇭"),
        Country("MK", "+389", "North Macedonia", "🇲🇰"),
        Country("ML", "+223", "Mali", "🇲🇱"),
        Country("MM", "+95", "Myanmar", "🇲🇲"),
        Country("MN", "+976", "Mongolia", "🇲🇳"),
        Country("MO", "+853", "Macau", "🇲🇴"),
        Country("MP", "+1", "Northern Mariana Islands", "🇲🇵"),
        Country("MQ", "+596", "Martinique", "🇲🇶"),
        Country("MR", "+222", "Mauritania", "🇲🇷"),
        Country("MS", "+1", "Montserrat", "🇲🇸"),
        Country("MT", "+356", "Malta", "🇲🇹"),
        Country("MU", "+230", "Mauritius", "🇲🇺"),
        Country("MV", "+960", "Maldives", "🇲🇻"),
        Country("MW", "+265", "Malawi", "🇲🇼"),
        Country("MX", "+52", "Mexico", "🇲🇽"),
        Country("MY", "+60", "Malaysia", "🇲🇾"),
        Country("MZ", "+258", "Mozambique", "🇲🇿"),
        Country("NA", "+264", "Namibia", "🇳🇦"),
        Country("NC", "+687", "New Caledonia", "🇳🇨"),
        Country("NE", "+227", "Niger", "🇳🇪"),
        Country("NF", "+672", "Norfolk Island", "🇳🇫"),
        Country("NG", "+234", "Nigeria", "🇳🇬"),
        Country("NI", "+505", "Nicaragua", "🇳🇮"),
        Country("NL", "+31", "Netherlands", "🇳🇱"),
        Country("NO", "+47", "Norway", "🇳🇴"),
        Country("NP", "+977", "Nepal", "🇳🇵"),
        Country("NR", "+674", "Nauru", "🇳🇷"),
        Country("NU", "+683", "Niue", "🇳🇺"),
        Country("NZ", "+64", "New Zealand", "🇳🇿"),
        Country("OM", "+968", "Oman", "🇴🇲"),
        Country("PA", "+507", "Panama", "🇵🇦"),
        Country("PE", "+51", "Peru", "🇵🇪"),
        Country("PF", "+689", "French Polynesia", "🇵🇫"),
        Country("PG", "+675", "Papua New Guinea", "🇵🇬"),
        Country("PH", "+63", "Philippines", "🇵🇭"),
        Country("PK", "+92", "Pakistan", "🇵🇰"),
        Country("PL", "+48", "Poland", "🇵🇱"),
        Country("PM", "+508", "Saint Pierre and Miquelon", "🇵🇲"),
        Country("PN", "+64", "Pitcairn Islands", "🇵🇳"),
        Country("PR", "+1", "Puerto Rico", "🇵🇷"),
        Country("PS", "+970", "Palestine", "🇵🇸"),
        Country("PT", "+351", "Portugal", "🇵🇹"),
        Country("PW", "+680", "Palau", "🇵🇼"),
        Country("PY", "+595", "Paraguay", "🇵🇾"),
        Country("QA", "+974", "Qatar", "🇶🇦"),
        Country("RE", "+262", "Reunion", "🇷🇪"),
        Country("RO", "+40", "Romania", "🇷🇴"),
        Country("RS", "+381", "Serbia", "🇷🇸"),
        Country("RU", "+7", "Russia", "🇷🇺"),
        Country("RW", "+250", "Rwanda", "🇷🇼"),
        Country("SA", "+966", "Saudi Arabia", "🇸🇦"),
        Country("SB", "+677", "Solomon Islands", "🇸🇧"),
        Country("SC", "+248", "Seychelles", "🇸🇨"),
        Country("SD", "+249", "Sudan", "🇸🇩"),
        Country("SE", "+46", "Sweden", "🇸🇪"),
        Country("SG", "+65", "Singapore", "🇸🇬"),
        Country("SH", "+290", "Saint Helena", "🇸🇭"),
        Country("SI", "+386", "Slovenia", "🇸🇮"),
        Country("SJ", "+47", "Svalbard and Jan Mayen", "🇸🇯"),
        Country("SK", "+421", "Slovakia", "🇸🇰"),
        Country("SL", "+232", "Sierra Leone", "🇸🇱"),
        Country("SM", "+378", "San Marino", "🇸🇲"),
        Country("SN", "+221", "Senegal", "🇸🇳"),
        Country("SO", "+252", "Somalia", "🇸🇴"),
        Country("SR", "+597", "Suriname", "🇸🇷"),
        Country("SS", "+211", "South Sudan", "🇸🇸"),
        Country("ST", "+239", "Sao Tome and Principe", "🇸🇹"),
        Country("SV", "+503", "El Salvador", "🇸🇻"),
        Country("SX", "+1", "Sint Maarten", "🇸🇽"),
        Country("SY", "+963", "Syria", "🇸🇾"),
        Country("SZ", "+268", "Eswatini", "🇸🇿"),
        Country("TC", "+1", "Turks and Caicos Islands", "🇹🇨"),
        Country("TD", "+235", "Chad", "🇹🇩"),
        Country("TG", "+228", "Togo", "🇹🇬"),
        Country("TH", "+66", "Thailand", "🇹🇭"),
        Country("TJ", "+992", "Tajikistan", "🇹🇯"),
        Country("TK", "+690", "Tokelau", "🇹🇰"),
        Country("TL", "+670", "East Timor", "🇹🇱"),
        Country("TM", "+993", "Turkmenistan", "🇹🇲"),
        Country("TN", "+216", "Tunisia", "🇹🇳"),
        Country("TO", "+676", "Tonga", "🇹🇴"),
        Country("TR", "+90", "Turkey", "🇹🇷"),
        Country("TT", "+1", "Trinidad and Tobago", "🇹🇹"),
        Country("TV", "+688", "Tuvalu", "🇹🇻"),
        Country("TW", "+886", "Taiwan", "🇹🇼"),
        Country("TZ", "+255", "Tanzania", "🇹🇿"),
        Country("UA", "+380", "Ukraine", "🇺🇦"),
        Country("UG", "+256", "Uganda", "🇺🇬"),
        Country("US", "+1", "United States", "🇺🇸"),
        Country("UY", "+598", "Uruguay", "🇺🇾"),
        Country("UZ", "+998", "Uzbekistan", "🇺🇿"),
        Country("VA", "+39", "Vatican City", "🇻🇦"),
        Country("VC", "+1", "Saint Vincent and the Grenadines", "🇻🇨"),
        Country("VE", "+58", "Venezuela", "🇻🇪"),
        Country("VG", "+1", "British Virgin Islands", "🇻🇬"),
        Country("VI", "+1", "U.S. Virgin Islands", "🇻🇮"),
        Country("VN", "+84", "Vietnam", "🇻🇳"),
        Country("VU", "+678", "Vanuatu", "🇻🇺"),
        Country("WF", "+681", "Wallis and Futuna", "🇼🇫"),
        Country("WS", "+685", "Samoa", "🇼🇸"),
        Country("YE", "+967", "Yemen", "🇾🇪"),
        Country("YT", "+262", "Mayotte", "🇾🇹"),
        Country("ZA", "+27", "South Africa", "🇿🇦"),
        Country("ZM", "+260", "Zambia", "🇿🇲"),
        Country("ZW", "+263", "Zimbabwe", "🇿🇼")
    )

    /**
     * Get country by dial code
     */
    fun getCountryByDialCode(dialCode: String): Country? {
        return countries.find { it.dialCode == dialCode }
    }

    /**
     * Get country by country code
     */
    fun getCountryByCode(code: String): Country? {
        return countries.find { it.code == code }
    }

    /**
     * Get default country (US)
     */
    fun getDefaultCountry(): Country {
        return countries.find { it.code == "US" } ?: countries.first()
    }
}
