name: Build Bits & Bytes demo for Push TFA (Develop)

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        default: 'develop'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Update signingConfigs in build.gradle.kts
      run: |
        sed -i '/signingConfigs {/,/}/c\signingConfigs {\n\n    getByName("debug") {\n        keyAlias = "${{ secrets.BITS_N_BYTES_DEBUG_KEY_ALIAS }}"\n        keyPassword = "${{ secrets.BITS_N_BYTES_DEBUG_KEY_PASSWORD }}"\n        storeFile = file("keystore/debug")\n        storePassword = "${{ secrets.BITS_N_BYTES_DEBUG_STORE_PASSWORD }}"\n    }\n' app/build.gradle.kts

    - name: Add API key/domain tags to strings.xml resource (demo only)
      run: |
        sed -i '/<\/resources>/i \    <string name="com.sap.cxcdc.apikey">${{ secrets.BITS_N_BYTES_DEMO_API_KEY_PUSH_TFA }}</string>' app/src/main/res/values/strings.xml
        sed -i '/<\/resources>/i \    <string name="com.sap.cxcdc.domain">us1.gigya.com</string>' app/src/main/res/values/strings.xml

    - name: Add Google required resources to strings.xml resource (actual value for demo only)
      run: |
        sed -i '/<\/resources>/i \    <string name="google_server_client_id">${{ secrets.GOOGLE_WEB_SERVER_CLIENT_ID }}</string>' app/src/main/res/values/strings.xml

    - name: Add Facebook required resources to strings.xml resource (actual value for demo only)
      run: |
        sed -i '/<\/resources>/i \    <string name="facebook_app_id">FB_APP_ID_HERE</string>' app/src/main/res/values/strings.xml
        sed -i '/<\/resources>/i \    <string name="fb_login_protocol_scheme">FB_LOGIN_PROTOCOL_SCHEME_HERE</string>' app/src/main/res/values/strings.xml
        sed -i '/<\/resources>/i \    <string name="facebook_client_token">FB_CLIENT_TOKEN_HERE</string>' app/src/main/res/values/strings.xml
        sed -i '/<\/resources>/i \    <string name="facebook_app_id">FB_APP_ID_HERE</string>' app/src/variant/res/values/strings.xml
        sed -i '/<\/resources>/i \    <string name="fb_login_protocol_scheme">FB_LOGIN_PROTOCOL_SCHEME_HERE</string>' app/src/variant/res/values/strings.xml
        sed -i '/<\/resources>/i \    <string name="facebook_client_token">FB_CLIENT_TOKEN_HERE</string>' app/src/variant/res/values/strings.xml

    - name: Add Line required resources to strings.xml resource (actual value for demo only)
      run: |
        sed -i '/<\/resources>/i \    <string name="line_channel_id">LINE_CHANNEL_ID_HERE</string>' app/src/main/res/values/strings.xml

    - name: Add WeChat required resources to strings.xml resource (actual value for demo only)
      run: |
        sed -i '/<\/resources>/i \    <string name="wechat_app_id">WECHAT_APP_ID_HERE</string>' app/src/main/res/values/strings.xml

    - name: Create file for google-services.json (Demo)
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

    - name: Build Debug APK
      run: ./gradlew assembleDemoDebug

    - name: Rename Demo APK file
      run: mv app/build/outputs/apk/demo/debug/app-demo-debug.apk app/build/outputs/apk/demo/debug/bits-n-bytes-app-demo-debug.apk

    - name: Upload Demo APK
      uses: actions/upload-artifact@v4
      with:
        name: demo-debug-apk
        path: app/build/outputs/apk/demo/debug/bits-n-bytes-app-demo-debug.apk
