name: Build Bits & Bytes demo debug APK

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        default: 'develop'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Update signingConfigs in build.gradle.kts
      run: |
        sed -i '/signingConfigs {/,/}/c\signingConfigs {\n\n    getByName("debug") {\n        keyAlias = "${{ secrets.BITS_N_BYTES_DEBUG_KEY_ALIAS }}"\n        keyPassword = "${{ secrets.BITS_N_BYTES_DEBUG_KEY_PASSWORD }}"\n        storeFile = file("keystore/debug")\n        storePassword = "${{ secrets.BITS_N_BYTES_DEBUG_STORE_PASSWORD }}"\n    }\n' app/build.gradle.kts

    - name: Change API key in strings.xml
      run: |
        sed -i 's|<string name="com.sap.cxcdc.apikey">.*</string>|<string name="com.sap.cxcdc.apikey">${{ secrets.BITS_N_BYTES_DEMO_API_KEY }}</string>|' app/src/main/res/values/strings.xml

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Rename APK file
      run: mv app/build/outputs/apk/demo/debug/app-demo-debug.apk app/build/outputs/apk/demo/debug/bits&bytes-app-demo-debug.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: app/build/outputs/apk/demo/debug/bits&bytes-app-demo-debug.apk